server:
  port: 8080
impresssol:
  broadband:
    tender:
      #      Normally jasypt would be used for encryption and the usernames and Password of the users should be inside the Database or LDAP
      security:
        admin-name: tenderAdmin
        admin-password: tenderAdmin
        webservice-name: tenderWS
        webservice-password: tenderWS
        kam-name: kam
        kam-password: kam
      repository:
        endpoint: api/repositories
#      Logging
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web: DEBUG
    org.springframework.ws.client.MessageTracing.sent: DEBUG
    org.springframework.ws.server.MessageTracing.sent: DEBUG
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE
  file: log/broadband-tender-demo.log
#  Health Monitoring
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"